#!/bin/sh

FG='#81a1c1'
BG='#3B4252'
FONT='Terminus:size=9'
#WIDTH='700'
HEIGHT='30'

NowPlaying(){
	tune=$(mpc current)
	echo "playing/$tune"
}

Version(){
	vers=$(uname -rs)
	echo os/$vers
}

Clock(){
	clk=$(date "+%r")
	echo time/$clk
}

Date(){
	dte=$(date "+%a %b %d")
	echo date/$dte
}

Packages(){
	pkg=$(pkg_info -q | wc -l | awk '{$1=$1};1')
	echo "pkg/$pkg"
}

Volume(){
	vol=$((`mixerctl -n outputs.master|cut -f 1 -d ','`*100/255))
	echo "vol/$vol%"
}

Battery(){
	batt=$(apm -l)
	echo "ac/$batt%"
}

while true; do
	sleep 1
	echo "$(Version)    $(Packages)    $(Volume)    $(Battery)    $(Date)    $(Clock)   " 
done | dzen2 -p -fn $FONT  -bg $BG -fg $FG -ta r -h $HEIGHT -y 0 -x 0 -e 'button2=;'
