#!/bin/sh

FG='#81A1C1'
BG='#3B4252'
FONT='Terminus:size=9'
WIDTH='500'
HEIGHT='30'

Version(){
	vers=$(uname -rs)
	echo $vers
}

Clock(){
	date "+%r"
}

Date(){
	date "+%a %b %d"
}

Packages(){
	pkg=$(pkg_info -q | wc -l | awk '{$1=$1};1')
	echo "pkg/$pkg"
}

Volume(){
	vol=$((`mixerctl -n outputs.master|cut -f 1 -d ','`*100/255))
	echo "vol/$vol%"
}

Battery(){
	batt=$(apm -l)
	echo "ac/$batt%"
}

while true; do
	sleep 1
	echo "$(Version)    $(Packages)    $(Volume)    $(Battery)    $(Date)    $(Clock)" 
done | dzen2 -p -fn $FONT -bg $BG -fg $FG -w $WIDTH -h $HEIGHT -y 0 -x 900 -e 'button2=;'
